const literaryQuotes = [
["El amor es la poesía de los sentidos.","Honoré de Balzac","La comédie humaine"],
["El corazón tiene sus razones que la razón no conoce.","Blaise Pascal","Pensées"],
["El verdadero amor nunca envejece.","Honoré de Balzac","La comédie humaine"],
["La felicidad está en el amor, no en otra parte.","George Sand","Indiana"],
["La vida es una flor cuyo amor es la miel.","Victor Hugo","Les Misérables"],
["Amar es actuar.","Victor Hugo","Les Misérables"],
["La esperanza es la palabra que Dios ha escrito en la frente de cada hombre.","Victor Hugo","Les Misérables"],
["La música es el lenguaje que no necesita palabras.","Victor Hugo","William Shakespeare"],
["La belleza es una forma de genio.","Stendhal","Le Rouge et le Noir"],
["Un hombre que no ama es un hombre que no vive.","Stendhal","Le Rouge et le Noir"],
["El amor es una flor que crece en todas partes.","Alexandre Dumas","Le Comte de Monte-Cristo"],
["Toda la felicidad de la vida consiste en amar y ser amado.","Alexandre Dumas","Le Comte de Monte-Cristo"],
["La amistad es un amor sin alas.","George Sand","Correspondance"],
["El recuerdo es el perfume del alma.","George Sand","Correspondance"],
["No hay nada más poderoso que una idea cuyo tiempo ha llegado.","Victor Hugo","Histoire d’un crime"],
["La libertad comienza donde termina la ignorancia.","Victor Hugo","Œuvres"],
["La tristeza es un muro entre dos jardines.","Khalil Gibran","Le Prophète"],
["La vida es una serie de encuentros.","Marcel Proust","À la recherche du temps perdu"],
["El verdadero viaje de descubrimiento no consiste en buscar nuevos paisajes.","Marcel Proust","À la recherche du temps perdu"],
["El único verdadero viaje es el cambio de mirada.","Marcel Proust","À la recherche du temps perdu"],
["El amor es el espacio y el tiempo hechos sensibles al corazón.","Marcel Proust","À la recherche du temps perdu"],
["Los días son quizá iguales para un reloj, pero no para un corazón.","Marcel Proust","À la recherche du temps perdu"],
["El recuerdo de las cosas pasadas no es necesariamente el recuerdo de las cosas como fueron.","Marcel Proust","À la recherche du temps perdu"],
["El tiempo perdido no se recupera, pero puede transformarse en memoria.","Marcel Proust","À la recherche du temps perdu"],
["Hay una dulzura en la tristeza que no existe en la alegría.","Victor Hugo","Les Travailleurs de la mer"],
["La melancolía es la felicidad de estar triste.","Victor Hugo","Les Travailleurs de la mer"],
["La noche ofrece a las estrellas una belleza que el día no conoce.","Victor Hugo","Les Misérables"],
["La conciencia es la presencia de Dios en el hombre.","Victor Hugo","Les Misérables"],
["El futuro tiene muchos nombres: para el débil es lo inalcanzable; para el valiente, la oportunidad.","Victor Hugo","Les Misérables"],
["La risa es el sol que ahuyenta el invierno del rostro humano.","Victor Hugo","Les Misérables"],
["La mayor felicidad de la vida es estar convencido de que somos amados.","Victor Hugo","Les Misérables"],
["La primera justicia es la conciencia.","Victor Hugo","Les Misérables"],
["La juventud es la sonrisa del porvenir ante un desconocido que es ella misma.","Victor Hugo","Les Misérables"],
["Nada despierta tanto la esperanza como una buena palabra.","Victor Hugo","Les Misérables"],
["La vida es una gran aventura hacia la luz.","Paul Claudel","Œuvres"],
["El amor no se mira con los ojos, sino con el alma.","William Shakespeare","Sueño de una noche de verano"],
["Somos hechos de la misma materia que nuestros sueños.","William Shakespeare","La tempestad"],
["El amor, al igual que la lluvia, no sabe de fronteras.","Colette","Œuvres"],
["Es necesario amar mucho para comprender mucho.","Colette","Œuvres"],
["La amistad es una planta que debe regarse.","Molière","Œuvres"],
["Es una gran miseria no tener suficiente espíritu para hablar bien ni suficiente juicio para callar.","La Rochefoucauld","Maximes"],
["La ausencia disminuye las pequeñas pasiones y enciende las grandes.","La Rochefoucauld","Maximes"],
["La verdadera amistad es como la salud: no sabemos apreciarla hasta perderla.","La Rochefoucauld","Maximes"],
["El amor propio es el mayor de todos los aduladores.","La Rochefoucauld","Maximes"],
["La felicidad es un sueño que se realiza despierto.","Alphonse de Lamartine","Méditations poétiques"],
["El hombre no tiene puerto, el tiempo no tiene orilla.","Alphonse de Lamartine","Le Lac"],
["Un solo ser os falta y todo queda despoblado.","Alphonse de Lamartine","L'Isolement"],
["¡Oh tiempo! suspende tu vuelo.","Alphonse de Lamartine","Le Lac"],
["Amar, es vivir; y vivir, es amar.","Alphonse de Lamartine","Méditations poétiques"],
["La poesía es la razón enloquecida.","Nicolas Boileau","L'Art poétique"],
["Nada es más dulce que la melancolía.","Victor Hugo","Les Contemplations"],
["Hay en todo hombre un poeta que ha muerto joven.","Charles Baudelaire","Les Fleurs du mal"],
["La naturaleza es un templo donde vivos pilares dejan salir a veces palabras confusas.","Charles Baudelaire","Les Fleurs du mal"],
["El hombre atraviesa bosques de símbolos que lo observan con miradas familiares.","Charles Baudelaire","Les Fleurs du mal"],
["Siempre hay en el alma humana un rincón donde florece la esperanza.","Charles Baudelaire","Œuvres"],
["Tu mirada contiene una noche más profunda que la noche.","Charles Baudelaire","Les Fleurs du mal"],
["Embriagaos de vino, de poesía o de virtud, como queráis.","Charles Baudelaire","Le Spleen de Paris"],
["Hay que estar siempre ebrio.","Charles Baudelaire","Le Spleen de Paris"],
["La vida es un hospital donde cada enfermo está poseído por el deseo de cambiar de cama.","Charles Baudelaire","Le Spleen de Paris"],
["El corazón tiene sus secretos que ninguna palabra puede revelar.","Gustave Flaubert","Madame Bovary"],
["La felicidad parece hecha para ser compartida.","Gustave Flaubert","Madame Bovary"],
["La vida es una larga espera de aquello que no llega.","Gustave Flaubert","Madame Bovary"],
["La ironía es una tristeza que no puede llorar.","Gustave Flaubert","Correspondance"],
["El alma es la que hace la belleza.","Gustave Flaubert","Correspondance"],
["Viajar hace modesta la imaginación.","Gustave Flaubert","Correspondance"],
["El corazón humano tiene infinitas habitaciones.","Guy de Maupassant","Une Vie"],
["El amor es siempre una alegría acompañada de miedo.","Guy de Maupassant","Une Vie"],
["La vida, ya lo ves, no es nunca tan buena ni tan mala como uno cree.","Guy de Maupassant","Une Vie"],
["Todo el mundo tiene su parte de soledad.","Guy de Maupassant","Une Vie"],
["La soledad es una compañera que nunca nos abandona.","Guy de Maupassant","Bel-Ami"],
["El alma tiene ilusiones como el pájaro tiene alas.","Victor Hugo","Les Misérables"],
["El amor es una parte del alma misma.","Victor Hugo","Les Misérables"],
["Amar a otra persona es verla como Dios la quiso.","Victor Hugo","Les Misérables"],
["La vida, la desgracia, el aislamiento, el abandono, la pobreza, son campos de batalla que tienen sus héroes.","Victor Hugo","Les Misérables"],
["La gratitud es una flor que nace en el alma.","Henryk Sienkiewicz","Œuvres"],
["La belleza es el comienzo del terror que todavía podemos soportar.","Rainer Maria Rilke","Duineser Elegien"],
["La paciencia lo es todo.","Rainer Maria Rilke","Cartas a un joven poeta"],
["Vive las preguntas ahora.","Rainer Maria Rilke","Cartas a un joven poeta"],
["Ama tus preguntas como habitaciones cerradas y como libros escritos en una lengua muy extraña.","Rainer Maria Rilke","Cartas a un joven poeta"],
["Quizá algún día, poco a poco, sin notarlo, vivamos dentro de la respuesta.","Rainer Maria Rilke","Cartas a un joven poeta"],
["La infancia es un reino donde nadie muere.","Stéphane Mallarmé","Œuvres"],
["Todo pensamiento emite una tirada de dados.","Stéphane Mallarmé","Un coup de dés"],
["La carne es triste, ¡ay!, y he leído todos los libros.","Stéphane Mallarmé","Brise marine"],
["La poesía se hace con palabras, no con ideas.","Stéphane Mallarmé","Œuvres"],
["El cielo está, el cielo está sobre el tejado.","Paul Verlaine","Sagesse"],
["De la música antes que nada.","Paul Verlaine","Art poétique"],
["Llora en mi corazón como llueve sobre la ciudad.","Paul Verlaine","Romances sans paroles"],
["La vida es sencilla y tranquila.","Paul Verlaine","Romances sans paroles"],
["El amor es una locura que todos conocemos.","Alfred de Musset","La Confession d'un enfant du siècle"],
["Todo lo que vivimos deja una huella.","Alfred de Musset","La Confession d'un enfant du siècle"],
["La vida es un sueño y el amor es su despertar.","Alfred de Musset","Œuvres"],
["La única verdad es amar.","Alfred de Musset","Poésies"],
["Hay placeres que nacen de la tristeza.","Alfred de Musset","Poésies"],
["El corazón de un hombre es un mar de secretos.","Alexandre Dumas","Les Trois Mousquetaires"],
["Uno para todos y todos para uno.","Alexandre Dumas","Les Trois Mousquetaires"],
["El tiempo es el único tesoro cuya pérdida es irreparable.","Alexandre Dumas","Le Comte de Monte-Cristo"],
["La felicidad está hecha de pequeñas cosas.","Alexandre Dumas","Œuvres"],
["La amistad duplica las alegrías y divide las penas.","Francis Bacon","Essais"],
["La vida es corta, pero el día es largo.","Jules Renard","Journal"],
["El amor es como un árbol: crece por sí mismo y hunde sus raíces profundamente.","Victor Hugo","Œuvres"],
["La palabra es el espejo del alma.","Proverbio literario francés","Tradición francesa"],
["El corazón tiene una memoria que la razón desconoce.","Honoré de Balzac","Œuvres"],
["Quien mira demasiado hacia atrás no ve lo que tiene delante.","Alexandre Dumas","Œuvres"],
["La ternura es la fuerza más silenciosa.","George Sand","Œuvres"],
["La esperanza es la única abeja que hace miel sin flores.","Robert Ingersoll","Œuvres"],
["La poesía es el eco de la melodía del universo en el corazón humano.","Alphonse de Lamartine","Œuvres"],
["El recuerdo es una presencia invisible.","Marcel Proust","À la recherche du temps perdu"],
["Una palabra amable puede cambiar el día entero.","Victor Hugo","Œuvres"],
["El amor transforma todo lo que toca.","Victor Hugo","Œuvres"],
["La belleza de las cosas existe en el espíritu de quien las contempla.","David Hume","Essais"],
["La vida florece allí donde encuentra ternura.","George Sand","Œuvres"],
["El corazón no envejece cuando conserva la capacidad de admirar.","George Sand","Œuvres"],
["La verdadera generosidad consiste en darlo todo y sentir que no se ha dado nada.","Albert Camus","L'Envers et l'Endroit"],
["En medio del invierno, aprendí que había en mí un verano invencible.","Albert Camus","Retour à Tipasa"],
["No ser amado es una desgracia; no amar es una tragedia.","Albert Camus","L'Été"],
["La belleza, sin duda, no hace las revoluciones, pero llega un día en que las revoluciones necesitan belleza.","Albert Camus","L'Homme révolté"],
["La vida no es más que una suma de elecciones.","Albert Camus","Le Mythe de Sisyphe"],
["La verdadera amistad comienza cuando el silencio entre dos personas es cómodo.","Noel Coward","Œuvres"],
["La noche está llena de estrellas que no vemos durante el día.","Victor Hugo","Œuvres"],
["El amor es la única pasión que no admite pasado ni futuro.","Honoré de Balzac","Œuvres"],
["La felicidad no es una estación a la que se llega, sino una manera de viajar.","Marguerite Yourcenar","Œuvres"],
["El silencio es también una forma de conversación.","Marguerite Yourcenar","Œuvres"]
];

// 🌍 Ampliación: literatura y pensamiento de distintas partes del mundo, presentada en español.
const worldLiteraryQuotes=[["El amor no mira con los ojos, sino con el alma.","William Shakespeare","Sueño de una noche de verano"],["Es mejor haber amado y perdido que jamás haber amado.","Alfred Lord Tennyson","In Memoriam"],["La esperanza es el sueño del hombre despierto.","Aristóteles","Obras"],["Quien tiene un porqué para vivir puede soportar casi cualquier cómo.","Friedrich Nietzsche","El crepúsculo de los ídolos"],["La vida debe ser comprendida hacia atrás. Pero debe ser vivida hacia adelante.","Søren Kierkegaard","Diarios"],["Todo lo que puedes imaginar es real.","Pablo Picasso","Atribuida"],["La belleza salvará al mundo.","Fiódor Dostoyevski","El idiota"],["El corazón tiene razones que la razón no entiende.","Blaise Pascal","Pensamientos"],["La música expresa aquello que no puede decirse con palabras.","Victor Hugo","Obras"],["No hay caminos para la paz; la paz es el camino.","Mahatma Gandhi","Atribuida"],["La libertad es siempre libertad para quien piensa diferente.","Rosa Luxemburgo","La revolución rusa"],["La paciencia es amarga, pero su fruto es dulce.","Jean-Jacques Rousseau","Emilio"],["La imaginación es más importante que el conocimiento.","Albert Einstein","Atribuida"],["La vida es realmente sencilla, pero insistimos en hacerla complicada.","Confucio","Analectas"],["La alegría no está en las cosas, está en nosotros.","Johann Wolfgang von Goethe","Obras"],["El amor es la poesía de los sentidos.","Honoré de Balzac","Obras"],["A veces el corazón ve lo que es invisible para los ojos.","Antoine de Saint-Exupéry","El Principito"],["Solo se ve bien con el corazón.","Antoine de Saint-Exupéry","El Principito"],["Lo esencial es invisible a los ojos.","Antoine de Saint-Exupéry","El Principito"],["La vida es una flor de la que el amor es la miel.","Victor Hugo","Obras"],["La felicidad depende de nosotros mismos.","Aristóteles","Ética a Nicómaco"],["El amor es la ausencia de juicio.","Dalai Lama","Enseñanzas"],["Donde hay amor hay vida.","Mahatma Gandhi","Atribuida"],["No llores porque terminó; sonríe porque sucedió.","Atribuida","Tradición literaria"],["El futuro pertenece a quienes creen en la belleza de sus sueños.","Eleanor Roosevelt","Atribuida"],["Después de todo, mañana será otro día.","Margaret Mitchell","Lo que el viento se llevó"],["Era el mejor de los tiempos, era el peor de los tiempos.","Charles Dickens","Historia de dos ciudades"],["Llámame Ismael.","Herman Melville","Moby-Dick"],["Todos los animales son iguales, pero algunos animales son más iguales que otros.","George Orwell","Rebelión en la granja"],["La única manera de hacer un amigo es serlo.","Ralph Waldo Emerson","Ensayos"],["El misterio de la vida no es un problema que resolver, sino una realidad que experimentar.","Albert Einstein","Atribuida"],["La noche es larga para quien espera.","William Shakespeare","Macbeth"],["El amor todo lo vence.","Virgilio","Églogas"],["Mientras haya vida, hay esperanza.","Proverbio latino","Tradición clásica"],["El destino mezcla las cartas y nosotros jugamos.","Arthur Schopenhauer","Parerga y Paralipómena"],["El tiempo es un gran autor, siempre encuentra un final perfecto.","Charles Chaplin","Atribuida"],["La poesía es verdad que se vuelve hermosa.","Robert Frost","A New Hampshire"],["La tierra tiene música para quienes escuchan.","William Shakespeare","El mercader de Venecia"]];
literaryQuotes.push(...worldLiteraryQuotes);
function initLiteraryQuotes(){
 const host=document.getElementById("literaryQuotes"),count=document.getElementById("quoteCount"),random=document.getElementById("quoteRandom");
 if(!host||!count||!Array.isArray(literaryQuotes)||!literaryQuotes.length){if(count)count.textContent="No hay frases disponibles.";return;}
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
 let current=-1,history=[];
 function show(index,save=true){
  current=((index%literaryQuotes.length)+literaryQuotes.length)%literaryQuotes.length;
  if(save && history[history.length-1]!==current)history.push(current);
  const q=literaryQuotes[current];
  count.textContent="Frase "+(current+1)+" de "+literaryQuotes.length;
  host.innerHTML='<article class="quote-card quote-featured"><div class="quote-mark">“</div><p>'+esc(q[0])+'</p><footer><strong>'+esc(q[1])+'</strong><span>'+esc(q[2])+'</span></footer></article><div class="quote-navigation"><button type="button" id="quotePrev" class="secondary" '+(history.length<2?'disabled':'')+'>← Anterior</button><button type="button" id="quoteNext" class="primary">Otra frase →</button></div>';
  document.getElementById("quotePrev").onclick=function(){if(history.length>1){history.pop();show(history[history.length-1],false);}};
  document.getElementById("quoteNext").onclick=function(){show(current+1,true);};
 }
 function randomQuote(){let next=Math.floor(Math.random()*literaryQuotes.length);while(literaryQuotes.length>1&&next===current)next=Math.floor(Math.random()*literaryQuotes.length);show(next,true);}
 if(random)random.onclick=randomQuote;
 show(Math.floor(Math.random()*literaryQuotes.length));
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initLiteraryQuotes);else initLiteraryQuotes();
